### ISSUE TITLE
Configuration options?

### ISSUE THREAD

**Issue by KoenVdB** [mlava/random-quote#1]
Hi, thanks for this extension!
Do you plan to provide configuration options in some future release?
The API provides features such as tags etc, so I hope these can be included.
In my case, I would search for 'stoicism'.

Thanks!

**Comment by mlava** [comment]
@KoenVdB will do. A bit swamped, but adding to the list. Cheers!

**Comment by mlava** [comment]
@KoenVdB thought about trying to implement this, but a call to 
`https://api.quotable.io/random?tags=stoicism`
returns only:
`{"statusCode":404,"statusMessage":"Could not find any matching quotes"}`

Can you point me to another quote collection with stoicism quotes as I might consider adding an alternative source to the extension.

**Comment by KoenVdB** [comment]
Hi,
I used https://stoic-quotes.com/api/quote before.
There is indeed no relevant tag for Stoicism in quotable.io ...

Thanks!
Koen

**Comment by mlava** [comment]
I've just submitted an update https://github.com/Roam-Research/roam-depot/pull/183.
It will need to be approved by the Roam guys, but then you can get get your stoic quotes either by command palette or smartblock. https://github.com/mlava/random-quote/blob/main/README.md
Cheers!

**Comment by KoenVdB** [comment]
Sounds great!
Keeping an eye on the depot.

Koen

On 5 Sep 2022, at 12:11 pm, Mark Lavercombe ***@***.***> wrote:


I've just submitted an update Roam-Research/roam-depot#183 <https://github.com/Roam-Research/roam-depot/pull/183>.
It will need to be approved by the Roam guys, but then you can get get your stoic quotes either by command palette or smartblock. https://github.com/mlava/random-quote/blob/main/README.md
Cheers!

**Comment by mlava** [comment]
@KoenVdB 
This update is now live in Roam Depot.
Let me know if any issues!

**Comment by KoenVdB** [comment]
Works perfectly!On 5. Sep 2022, at 12:11, Mark Lavercombe ***@***.***> wrote:﻿
I've just submitted an update Roam-Research/roam-depot#183.
It will need to be approved by the Roam guys, but then you can get get your stoic quotes either by command palette or smartblock. https://github.com/mlava/random-quote/blob/main/README.md
Cheers!

**Comment by KoenVdB** [comment]
Hi Mark,

The one I used before is : https://stoic-quotes.com/api/quote

This was my code before in a SmartBlock:
$.ajax(settings).done(async function (response) {
  var jsonQuotes = JSON.stringify(response);
  var quote = JSON.parse(jsonQuotes);
  let string = "> ";
  string += quote.text;
  string += " [[";
  string += quote.author;
  string += "]] #quote";
  await roam42.common.createSiblingBlock(startBlock, string, true);
  await roam42.common.deleteBlock(startBlock);

On 3 Sep 2022, at 1:34 am, Mark Lavercombe ***@***.***> wrote:


@KoenVdB <https://github.com/KoenVdB> thought about trying to implement this, but a call to
https://api.quotable.io/random?tags=stoicism
returns only:
{"statusCode":404,"statusMessage":"Could not find any matching quotes"}

Can you point me to another quote collection with stoicism quotes as I might consider adding an alternative source to the extension.
